[build]
  base = "Frontend"
  publish = "Frontend/build"
  command = "npm run build"

[secrets]
  scan_omit_keys = ["REACT_APP_API_URL", "REACT_APP_GOOGLE_CLIENT_ID", "REACT_APP_GOOGLE_CLIENT_SECRET"]
